package com.thepos.biz.utils;


public class Constant {

    public static boolean isDebug = true;
    public static final String VIEWINDEX = "viewindex";
    public static final String CARDNUMBER = "cardNumber";
    public static final String CLICKFUNC = "clickFunc";
    public static final String FUNCNAME = "funcName";
    public static final String PSW = "psw";
    public static final String PSWENC = "pswEnc";
    public static final String PINBLOCKTYPE = "PinBlockType";
    public static final int CHECKBALANCERESULT = 0;
    public static final String POSINFO = "posinfo";

    //交易类型
    public static final String SIGN_IN = "0"; //签到
    public static final String CONSUME = "2"; //消费
    public static final String REVOKE = "3"; //撤销
    public static final String QUERY = "4"; //查余
    public static final String REVERSAL = "5"; //冲正

    //加密报文信息插入标识码
    public static final char ENC_INSERT_C2 = 0x80;//插入磁道2信息
    public static final char ENC_INSERT_C3 = 0x40;//插入磁道3信息
    public static final char ENC_INSERT_Z1 = 0x20;//插入账户1信息

    /*基于pboc应用的交易和
     * 基于UPcard应用的交易元素标示，应用于PAA格式数据*/
    public static final int TYPE_APPLY_NAME = 1;//支付应用名称
    public static final int TYPE_VERSION_NUMBER = 2;//版本号
    public static final int TYPE_TRADE_MOLD = 3;//交易类型
    public static final int TYPE_TRADE_UPTIME = 4;//交易提交时间
    public static final int TYPE_SUPPLIER_CODE = 5;//商户代码
    public static final int TYPE_SUPPLIER_NAME = 6;//商户名称
    public static final int TYPE_SUPPLIER_COUNTRY_CODE = 7;//商户国家代码
    public static final int TYPE_TERMINAL_CODE = 8;//子商户/终端代码
    public static final int TYPE_INDENT_NUMBER = 9;//订单号
    public static final int TYPE_AUDIT_DATE = 10;//清算日期
    public static final int TYPE_TRADE_MONEY = 11;//交易金额
    public static final int TYPE_TRADE_MONEY_TYPE = 12;//交易币种
    public static final int TYPE_CONSUME_MONEY = 13;//扣帐金额
    public static final int TYPE_CONSUME_COIN = 14;//扣账币种
    public static final int TYPE_CONSUME_PARITIES = 15;//扣帐汇率
    public static final int TYPE_ACCOUNT_1 = 16;//账户1
    public static final int TYPE_ACCOUNT_ID = 17;//个人身份标识码
    public static final int TYPE_ANSWER_NUMBER = 19;//应答码
    public static final int TYPE_FIRST_TRADE_TIME = 20;//原始交易提交时间
    public static final int TYPE_TRADE_NUMBER = 24;//交易流水号
    public static final int TYPE_GALLERY2_INFO = 25;//磁道2数据
    public static final int TYPE_GALLERY3_INFO = 26;//磁道3数据
    public static final int TYPE_USER_INFO = 27;//持卡人身份信息
    public static final int TYPE_TERMINAL_CHIP_NUMBER = 28;//终端芯片序列号
    public static final int TYPE_CMSP_SPARE = 29;//CMSP保留使用
    public static final int TYPE_BALANCE = 30;//账户余额
    public static final int TYPE_BALANCE_COIN = 31;//账户余额币种
    public static final int TYPE_ACCOUNT_2 = 33;//账户2
    public static final int TYPE_CARD_VALIDITY = 34;//卡有效期
    public static final int TYPE_SERVE_INFO = 35;//服务信息
    public static final int TYPE_DYNAMI_SECRETKEY_INFO = 36;//动态密钥数据
    public static final int TYPE_SAFETY_TYPE = 37;//安全载体类型
    public static final int TYPE_SP_CODE = 38;//SP代码
    public static final int TYPE_CARD_ID = 39;//卡片序列号
    public static final int TYPE_SYSTEM_SUPPORT = 40;//系统支持方
    public static final int TYPE_FIRST_TRADE_NUMBER = 41;//原交易流水号
    public static final int TYPE_CREDITCARD_BALANCE = 42;//信用卡账户余额
    public static final int TYPE_CREDITCARD_BALANCE_COIN = 43;//信用卡账户余额币种
    public static final int TYPE_JDJ_APPLY_INFO = 251;//借贷记应用数据
    public static final int TYPE_SUPPLIER_ABSTRACT_INFO = 252;//商户摘要数据
    public static final int TYPE_SUPPLIER_AUTOGRAPH = 253;//商户数字签名
    public static final int TYPE_SEND_AUTOGRAPH = 254;//发送方数字签名
    public static final int TYPE_MESSAGE_IDENTUFY = 255;//报文鉴别码

    //8583报文域值
    public static final int TYPE_8583_key_1 = 1;
    public static final int TYPE_8583_key_2 = 2;
    public static final int TYPE_8583_key_3 = 3;
    public static final int TYPE_8583_key_4 = 4;
    public static final int TYPE_8583_key_5 = 5;
    public static final int TYPE_8583_key_6 = 6;
    public static final int TYPE_8583_key_7 = 7;
    public static final int TYPE_8583_key_8 = 8;
    public static final int TYPE_8583_key_9 = 9;
    public static final int TYPE_8583_key_10 = 10;
    public static final int TYPE_8583_key_11 = 11;
    public static final int TYPE_8583_key_12 = 12;
    public static final int TYPE_8583_key_13 = 13;
    public static final int TYPE_8583_key_14 = 14;
    public static final int TYPE_8583_key_15 = 15;
    public static final int TYPE_8583_key_16 = 16;
    public static final int TYPE_8583_key_17 = 17;
    public static final int TYPE_8583_key_18 = 18;
    public static final int TYPE_8583_key_19 = 19;
    public static final int TYPE_8583_key_20 = 20;
    public static final int TYPE_8583_key_21 = 21;
    public static final int TYPE_8583_key_22 = 22;
    public static final int TYPE_8583_key_23 = 23;
    public static final int TYPE_8583_key_24 = 24;
    public static final int TYPE_8583_key_25 = 25;
    public static final int TYPE_8583_key_26 = 26;
    public static final int TYPE_8583_key_27 = 27;
    public static final int TYPE_8583_key_28 = 28;
    public static final int TYPE_8583_key_29 = 29;
    public static final int TYPE_8583_key_30 = 30;
    public static final int TYPE_8583_key_31 = 31;
    public static final int TYPE_8583_key_32 = 32;
    public static final int TYPE_8583_key_33 = 33;
    public static final int TYPE_8583_key_34 = 34;
    public static final int TYPE_8583_key_35 = 35;
    public static final int TYPE_8583_key_36 = 36;
    public static final int TYPE_8583_key_37 = 37;
    public static final int TYPE_8583_key_38 = 38;
    public static final int TYPE_8583_key_39 = 39;
    public static final int TYPE_8583_key_40 = 40;
    public static final int TYPE_8583_key_41 = 41;
    public static final int TYPE_8583_key_42 = 42;
    public static final int TYPE_8583_key_43 = 43;
    public static final int TYPE_8583_key_44 = 44;
    public static final int TYPE_8583_key_45 = 45;
    public static final int TYPE_8583_key_46 = 46;
    public static final int TYPE_8583_key_47 = 47;
    public static final int TYPE_8583_key_48 = 48;
    public static final int TYPE_8583_key_49 = 49;
    public static final int TYPE_8583_key_50 = 50;
    public static final int TYPE_8583_key_51 = 51;
    public static final int TYPE_8583_key_52 = 52;
    public static final int TYPE_8583_key_53 = 53;
    public static final int TYPE_8583_key_54 = 54;
    public static final int TYPE_8583_key_55 = 55;
    public static final int TYPE_8583_key_56 = 56;
    public static final int TYPE_8583_key_57 = 57;
    public static final int TYPE_8583_key_58 = 58;
    public static final int TYPE_8583_key_59 = 59;
    public static final int TYPE_8583_key_60 = 60;
    public static final int TYPE_8583_key_61 = 61;
    public static final int TYPE_8583_key_62 = 62;
    public static final int TYPE_8583_key_63 = 63;
    public static final int TYPE_8583_key_64 = 64;
    public static final int TYPE_8583_key_65 = 65;
    public static final int TYPE_8583_key_66 = 66;
    public static final int TYPE_8583_key_67 = 67;
    public static final int TYPE_8583_key_68 = 68;
    public static final int TYPE_8583_key_69 = 69;
    public static final int TYPE_8583_key_70 = 70;
    public static final int TYPE_8583_key_71 = 71;
    public static final int TYPE_8583_key_72 = 72;
    public static final int TYPE_8583_key_73 = 73;
    public static final int TYPE_8583_key_74 = 74;
    public static final int TYPE_8583_key_75 = 75;
    public static final int TYPE_8583_key_76 = 76;
    public static final int TYPE_8583_key_77 = 77;
    public static final int TYPE_8583_key_78 = 78;
    public static final int TYPE_8583_key_79 = 79;
    public static final int TYPE_8583_key_80 = 80;
    public static final int TYPE_8583_key_81 = 81;
    public static final int TYPE_8583_key_82 = 82;
    public static final int TYPE_8583_key_83 = 83;
    public static final int TYPE_8583_key_84 = 84;
    public static final int TYPE_8583_key_85 = 85;
    public static final int TYPE_8583_key_86 = 86;
    public static final int TYPE_8583_key_87 = 87;
    public static final int TYPE_8583_key_88 = 88;
    public static final int TYPE_8583_key_89 = 89;
    public static final int TYPE_8583_key_90 = 70;
    public static final int TYPE_8583_key_91 = 91;
    public static final int TYPE_8583_key_92 = 92;
    public static final int TYPE_8583_key_93 = 93;
    public static final int TYPE_8583_key_94 = 94;
    public static final int TYPE_8583_key_95 = 95;
    public static final int TYPE_8583_key_96 = 96;
    public static final int TYPE_8583_key_97 = 97;
    public static final int TYPE_8583_key_98 = 98;
    public static final int TYPE_8583_key_99 = 99;
    public static final int TYPE_8583_key_100 = 100;
    public static final int TYPE_8583_key_101 = 101;
    public static final int TYPE_8583_key_102 = 102;
    public static final int TYPE_8583_key_103 = 103;
    public static final int TYPE_8583_key_104 = 104;
    public static final int TYPE_8583_key_105 = 105;
    public static final int TYPE_8583_key_106 = 106;
    public static final int TYPE_8583_key_107 = 107;
    public static final int TYPE_8583_key_108 = 108;
    public static final int TYPE_8583_key_109 = 109;
    public static final int TYPE_8583_key_110 = 110;
    public static final int TYPE_8583_key_111 = 111;
    public static final int TYPE_8583_key_112 = 112;
    public static final int TYPE_8583_key_113 = 113;
    public static final int TYPE_8583_key_114 = 114;
    public static final int TYPE_8583_key_115 = 115;
    public static final int TYPE_8583_key_116 = 116;
    public static final int TYPE_8583_key_117 = 117;
    public static final int TYPE_8583_key_118 = 118;
    public static final int TYPE_8583_key_119 = 119;
    public static final int TYPE_8583_key_120 = 120;
    public static final int TYPE_8583_key_121 = 121;
    public static final int TYPE_8583_key_122 = 122;
    public static final int TYPE_8583_key_123 = 123;
    public static final int TYPE_8583_key_124 = 124;
    public static final int TYPE_8583_key_125 = 125;
    public static final int TYPE_8583_key_126 = 126;
    public static final int TYPE_8583_key_127 = 127;
    public static final int TYPE_8583_key_128 = 128;

    //post访问网络的handle变量
    public static final int jsonPost = 0;//开始联网获取数据
    public static final int jsonResultSuccess = 1;//成功获取数据
    public static final int jsonResultFail = 2;//获取数据失败

    //交易信息返回状态码
    public static final String TRADE_RESPONSECODE_00 = "00";//交易成功
    //	public static final String TRADE_RESPONSECODE_01 = "01";//发卡方原因拒绝该笔交易
//	public static final String TRADE_RESPONSECODE_03 = "03";//无效商户
    public static final String TRADE_RESPONSECODE_04 = "04";//无法找到匹配的原交易
    //	public static final String TRADE_RESPONSECODE_05 = "05";//报文合法性验证失败
    public static final String TRADE_RESPONSECODE_06 = "06";//余额不足
    public static final String TRADE_RESPONSECODE_07 = "07";//下一节点返回失败应答
    public static final String TRADE_RESPONSECODE_13 = "13";//无效金额
    public static final String TRADE_RESPONSECODE_14 = "14";//无效卡号（无此账号）
    public static final String TRADE_RESPONSECODE_15 = "15";//无此发卡方
    public static final String TRADE_RESPONSECODE_38 = "38";//超过允许的PIN试输入
    public static final String TRADE_RESPONSECODE_40 = "40";//请求的功能尚不支持
    public static final String TRADE_RESPONSECODE_51 = "51";//资金不足
    public static final String TRADE_RESPONSECODE_54 = "54";//过期的卡
    public static final String TRADE_RESPONSECODE_55 = "55";//不正确的PIN
    public static final String TRADE_RESPONSECODE_57 = "57";//不允许持卡人进行的交易
    public static final String TRADE_RESPONSECODE_61 = "61";//超出金额限制
    public static final String TRADE_RESPONSECODE_62 = "62";//受限制的卡
    public static final String TRADE_RESPONSECODE_64 = "64";//原始金额错误
    public static final String TRADE_RESPONSECODE_65 = "65";//超出取款/消费次数限制
    public static final String TRADE_RESPONSECODE_68 = "68";//发卡行响应超时
    public static final String TRADE_RESPONSECODE_75 = "75";//允许的输入PIN次数超限
    public static final String TRADE_RESPONSECODE_91 = "91";//发卡方不能操作
    public static final String TRADE_RESPONSECODE_94 = "94";//重复交易
    public static final String TRADE_RESPONSECODE_96 = "96";//银联处理中心系统异常、失效
    public static final String TRADE_RESPONSECODE_98 = "98";//银联处理中心收不到发卡方应答
    public static final String TRADE_RESPONSECODE_99 = "99";//本节点系统异常，无法提供服务
    public static final String TRADE_RESPONSECODE_A0 = "A0";//MAC鉴别失败
    public static final String TRADE_RESPONSECODE_Y3 = "Y3";//挂失的介质，需要解挂操作

    public static final String TRADE_RESPONSECODE_X0 = "X0";//VIPOS要删除的账号不存在（委托关系不存在）
    public static final String TRADE_RESPONSECODE_X1 = "X1";//取得流水号错误
    public static final String TRADE_RESPONSECODE_X2 = "X2";//平台休息
    public static final String TRADE_RESPONSECODE_X3 = "X3";//黑名单
    public static final String TRADE_RESPONSECODE_X4 = "X4";//无交易权限
    public static final String TRADE_RESPONSECODE_X5 = "X5";//记录日志错误
    public static final String TRADE_RESPONSECODE_X6 = "X6";//报文格式错误
    public static final String TRADE_RESPONSECODE_X7 = "X7";//预授权类交易未匹配原交易
    public static final String TRADE_RESPONSECODE_X8 = "X8";//计算MAC错误
    public static final String TRADE_RESPONSECODE_X9 = "X9";//报文发送失败
    public static final String TRADE_RESPONSECODE_XA = "XA";//系统错误
    public static final String TRADE_RESPONSECODE_XB = "XB";//关键字段加密失败
    public static final String TRADE_RESPONSECODE_XC = "XC";//关键字段解密失败
    public static final String TRADE_RESPONSECODE_XD = "XD";//磁道解密失败
    public static final String TRADE_RESPONSECODE_XE = "XE";//PIN转加密失败
    public static final String TRADE_RESPONSECODE_XF = "XF";//报文生成错误
    public static final String TRADE_RESPONSECODE_XG = "XG";//状态失败，不能冲正
    public static final String TRADE_RESPONSECODE_XH = "XH";//不能匹配原交易
    public static final String TRADE_RESPONSECODE_XI = "XI";//单笔交易金额超限
    public static final String TRADE_RESPONSECODE_XJ = "XJ";//总交易金额超限
    public static final String TRADE_RESPONSECODE_XK = "XK";//CUPS/第三方超时
    public static final String TRADE_RESPONSECODE_XL = "XL";//MPI超时
    public static final String TRADE_RESPONSECODE_XM = "XM";//重复交易（重复建立委托）
    public static final String TRADE_RESPONSECODE_XN = "XN";//CUPS拒绝
    public static final String TRADE_RESPONSECODE_XP = "XP";//退货和撤销未匹配原交易
    public static final String TRADE_RESPONSECODE_XQ = "XQ";//退货和撤销金额错误
    public static final String TRADE_RESPONSECODE_XR = "XR";//信用卡卡号检验错误
    public static final String TRADE_RESPONSECODE_XS = "XS";//转账/信用卡还款转出卡为贷记卡
    public static final String TRADE_RESPONSECODE_XT = "XT";//卡BIN信息不存在
    public static final String TRADE_RESPONSECODE_XU = "XU";//VIPOS达到最大删除限制次数
    public static final String TRADE_RESPONSECODE_XV = "XV";//VIPOS绑卡数量超过限制
    public static final String TRADE_RESPONSECODE_01 = "01";//无卡预约错误
    public static final String TRADE_RESPONSECODE_02 = "02";//无卡预约错误
    public static final String TRADE_RESPONSECODE_03 = "03";//无卡预约错误
    public static final String TRADE_RESPONSECODE_05 = "05";//未找到预约信息
    public static final String TRADE_RESPONSECODE_NR = "NR";//网络连接异常或服务器无响应
    //错误信息提示字符串，与上面的错误状态码对应
//	public static final String TRADE_RESPONSECODE_01_ESTR = "发卡方原因拒绝该笔交易";
//	public static final String TRADE_RESPONSECODE_03_ESTR = "无效商户";
    public static final String TRADE_RESPONSECODE_04_ESTR = "无法找到匹配的原交易";
    //	public static final String TRADE_RESPONSECODE_05_ESTR = "报文合法性验证失败";
    public static final String TRADE_RESPONSECODE_06_ESTR = "余额不足";
    public static final String TRADE_RESPONSECODE_07_ESTR = "下一节点返回失败应答";
    public static final String TRADE_RESPONSECODE_13_ESTR = "无效金额";
    public static final String TRADE_RESPONSECODE_14_ESTR = "无效卡号（无此账号）";
    public static final String TRADE_RESPONSECODE_15_ESTR = "无此发卡方";
    public static final String TRADE_RESPONSECODE_38_ESTR = "超过允许的PIN试输入";
    public static final String TRADE_RESPONSECODE_40_ESTR = "请求的功能尚不支持";
    public static final String TRADE_RESPONSECODE_51_ESTR = "资金不足";
    public static final String TRADE_RESPONSECODE_54_ESTR = "过期的卡";
    public static final String TRADE_RESPONSECODE_55_ESTR = "不正确的PIN";
    public static final String TRADE_RESPONSECODE_57_ESTR = "不允许持卡人进行的交易";
    public static final String TRADE_RESPONSECODE_61_ESTR = "超出金额限制";
    public static final String TRADE_RESPONSECODE_62_ESTR = "受限制的卡";
    public static final String TRADE_RESPONSECODE_64_ESTR = "原始金额错误";
    public static final String TRADE_RESPONSECODE_65_ESTR = "超出取款/消费次数限制";
    public static final String TRADE_RESPONSECODE_68_ESTR = "发卡行响应超时";
    public static final String TRADE_RESPONSECODE_75_ESTR = "允许的输入PIN次数超限";
    public static final String TRADE_RESPONSECODE_91_ESTR = "发卡方不能操作";
    public static final String TRADE_RESPONSECODE_94_ESTR = "重复交易";
    public static final String TRADE_RESPONSECODE_96_ESTR = "银联处理中心系统异常、失效";
    public static final String TRADE_RESPONSECODE_98_ESTR = "银联处理中心收不到发卡方应答";
    public static final String TRADE_RESPONSECODE_99_ESTR = "本节点系统异常，无法提供服务";
    public static final String TRADE_RESPONSECODE_A0_ESTR = "MAC鉴别失败";
    public static final String TRADE_RESPONSECODE_Y3_ESTR = "挂失的介质，需要解挂操作";

    public static final String TRADE_RESPONSECODE_X0_ESTR = "VIPOS要删除的账号不存在（委托关系不存在）";
    public static final String TRADE_RESPONSECODE_X1_ESTR = "取得流水号错误";
    public static final String TRADE_RESPONSECODE_X2_ESTR = "平台休息";
    public static final String TRADE_RESPONSECODE_X3_ESTR = "黑名单";
    public static final String TRADE_RESPONSECODE_X4_ESTR = "无交易权限";
    public static final String TRADE_RESPONSECODE_X5_ESTR = "记录日志错误";
    public static final String TRADE_RESPONSECODE_X6_ESTR = "报文格式错误";
    public static final String TRADE_RESPONSECODE_X7_ESTR = "预授权类交易未匹配原交易";
    public static final String TRADE_RESPONSECODE_X8_ESTR = "计算MAC错误";
    public static final String TRADE_RESPONSECODE_X9_ESTR = "报文发送失败";
    public static final String TRADE_RESPONSECODE_XA_ESTR = "系统错误";
    public static final String TRADE_RESPONSECODE_XB_ESTR = "关键字段加密失败";
    public static final String TRADE_RESPONSECODE_XC_ESTR = "关键字段解密失败";
    public static final String TRADE_RESPONSECODE_XD_ESTR = "磁道解密失败";
    public static final String TRADE_RESPONSECODE_XE_ESTR = "PIN转加密失败";
    public static final String TRADE_RESPONSECODE_XF_ESTR = "报文生成错误";
    public static final String TRADE_RESPONSECODE_XG_ESTR = "状态失败，不能冲正";
    public static final String TRADE_RESPONSECODE_XH_ESTR = "不能匹配原交易";
    public static final String TRADE_RESPONSECODE_XI_ESTR = "单笔交易金额超限";
    public static final String TRADE_RESPONSECODE_XJ_ESTR = "总交易金额超限";
    public static final String TRADE_RESPONSECODE_XK_ESTR = "CUPS/第三方超时";
    public static final String TRADE_RESPONSECODE_XL_ESTR = "MPI超时";
    public static final String TRADE_RESPONSECODE_XM_ESTR = "重复交易（重复建立委托）";
    public static final String TRADE_RESPONSECODE_XN_ESTR = "CUPS拒绝";
    public static final String TRADE_RESPONSECODE_XP_ESTR = "退货和撤销未匹配原交易";
    public static final String TRADE_RESPONSECODE_XQ_ESTR = "退货和撤销金额错误";
    public static final String TRADE_RESPONSECODE_XR_ESTR = "信用卡卡号检验错误";
    public static final String TRADE_RESPONSECODE_XS_ESTR = "转账/信用卡还款转出卡为贷记卡";
    public static final String TRADE_RESPONSECODE_XT_ESTR = "卡BIN信息不存在";
    public static final String TRADE_RESPONSECODE_XU_ESTR = "VIPOS达到最大删除限制次数";
    public static final String TRADE_RESPONSECODE_XV_ESTR = "VIPOS绑卡数量超过限制";
    public static final String TRADE_RESPONSECODE_01_ESTR = "无卡预约错误";
    public static final String TRADE_RESPONSECODE_02_ESTR = "无卡预约错误";
    public static final String TRADE_RESPONSECODE_03_ESTR = "无卡预约错误";
    public static final String TRADE_RESPONSECODE_05_ESTR = "未找到预约信息";
    public static final String TRADE_RESPONSECODE_NR_ESTR = "网络连接异常或服务器无响应";

    //网络请求关键字
    public static final String APPTAG = "appTag";
    public static final String TRANSTYPE = "transType";
    public static final String UPDATEFLAG = "updateFlag";
    public static final String PLATFORM = "platform";
    public static final String APPVER = "appVer";
    public static final String SERIALNO = "serialNo";
    public static final String REQDATE = "reqDate";
    public static final String REQTIME = "reqTime";
    public static final String TRANSNO = "transNo";
    public static final String PACKAGETYPE = "packageType";
    public static final String PACKAGEDATA = "packageData";
}
